
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.1.0/24
  ip_ban_whitelist:
    - 192.168.0.0/16
    - 10.0.0.0/8
    - 172.16.0.0/12

lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: OpenHEMS
      icon: mdi:script
      show_in_sidebar: true
      filename: dashboards.yaml

# https://www.home-assistant.io/integrations/template/
# For EMHASS
template: !include template.yaml

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
