api:
  url: http://192.168.1.202:8123/api
  long_lived_token: "Put your secret token here"
  ssl_certificate: "Your SSL Certificate"
localization:
  latitude: 48.430883803968456
  longitude: -2.2153649964972693
  altitude: 100
  timeZone: Europe/Paris
server:
  loglevel: debug
  loopDelay: 10
  network: homeassistant # Define the type of network API used to control the home energy.
  strategies: # Define the algorithm used to control the  home energy.
    - {class: offpeak, id: offpeak}
    - {class: switchoff, id: redDay, offrange: [ "6h-22h"], condition: "self.getVal('sensor.rte_tempo_couleur_actuelle')=='Rouge'"}
network:
  nodes:
    - {id: linky, currentPower: sensor.lixee_zlinky_tic_puissance_apparente, marginPower: 1000, maxPower: 5000, minPower: 0, class: PublicPowerGrid,
        contract: {class: RTETempo}
      }
    - {id: voiture, strategy: offpeak, class: switch, isOn: switch.tz3000_2putqrmw_ts011f_commutateur_2, currentPower: sensor.tz3000_2putqrmw_ts011f_puissance_2, maxPower: 2300,
        sensor: sensor.tz3000_2putqrmw_ts011f_puissance, target: [["22h-6h", 16], ["6h-22h", 19]], constraints: {maxPower: 2300, maxDurationOn: 600} }
    - {id: box, strategy: redDay, class: switch, currentPower: sensor.tz3000_2putqrmw_ts011f_puissance}

