api:
  url: http://192.168.1.202:8123/api
  long_lived_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmOTM4ZTFmY2FjNTA0MWEyYWZkYjEyOGYyYTJlNGNmYiIsImlhdCI6MTcyNjU2NTU1NiwiZXhwIjoyMDQxOTI1NTU2fQ.3DdEXGsM3cg5NgMUKj2k5FsEG07p2AkRF_Ad-CljSTQ"
  ssl_certificate: /etc/letsencrypt/live/openproduct.freeboxos.fr/cert.pem
latitude: 48.430883803968456
longitude: -2.2153649964972693
altitude: 100
timeZone: Europe/Paris
server:
  # logformat: Optional default is "%(levelname)s : %(asctime)s : %(message)s", for custom configuration see https://docs.python.org/3/library/logging.html#logrecord-attributes
  logfile: openhems.log # Optional, default is /var/log/openhems.log
  # loglevel: Optional, default is info, availables are debug / info / warn / error / critical / no
  loopDelay: 30 # interval beetween 2
  network: homeassistant # Define the type of network API used to control the home energy.
  strategy: offpeak # Define the algorithm used to control the  home energy.
network:
  nodes:
    - {id: linky, currentPower: sensor.lixee_zlinky_tic_puissance_apparente, powerMargin: 1000, maxPower: 10000, minPower: 0, class: PublicPowerGrid, contract: {class: RTETempoContract, color: sensor.rte_tempo_couleur_actuelle} }
    - {id: voiture, class: switch, isOn: switch.tz3000_2putqrmw_ts011f_commutateur_2, currentPower: sensor.tz3000_2putqrmw_ts011f_puissance_2, maxPower:2000}
