api:
  long_lived_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmOTM4ZTFmY2FjNTA0MWEyYWZkYjEyOGYyYTJlNGNmYiIsImlhdCI6MTcyNjU2NTU1NiwiZXhwIjoyMDQxOTI1NTU2fQ.3DdEXGsM3cg5NgMUKj2k5FsEG07p2AkRF_Ad-CljSTQ
  ssl_certificate: /etc/letsencrypt/live/openproduct.freeboxos.fr/cert.pem
default:
  node:
    publicpowergrid:
      contract:
        generic:
          offpeakhoursranges: ''
network:
  nodes:
  - capacity: '10000'
    class: battery
    currentLevel: None
    currentPower: None
    efficiencyIn: '0.95'
    efficiencyOut: '0.95'
    highLevel: '0.8'
    id: id01
    lowLevel: '0.2'
    maxPowerIn: '2000'
    maxPowerOut: '2000'
    targetLevel: '0.75'
  - class: publicpowergrid
    contract:
      class: generic
      defaultPrice: '0.1'
      id: null
      offpeakhoursranges: '["06h-22h",0.12]'
      outRangePrice: '1'
      sellprice: '0'
    currentPower: ''
    id: id11
    marginPower: '1000'
    maxPower: '6000'
    minPower: '0'
server:
  loglevel: debug
  strategies:
  - class: offpeak
    id: offpeak
    offpeakhours: None
