name: Run tests and upload coverage

on: 
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
          pip install pytest pytest-cov setuptools
          python setup.py install
          PWD=$(pwd)
          export PYTHONPATH=$PWD/src:$PWD/lib/emhass/src/:$PYTHONPATH
          echo "PYTHONPATH=$PYTHONPATH"
          echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV

      - name: Run tests
        run: pytest --cov

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
