# Inspired by
# https://docs.docker.com/build/ci/github-actions/multi-platform/
# template modified from: https://docs.docker.com/build/ci/github-actions/multi-platform/ & https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images
# docker run --rm -it ghcr.io/abriotde/openhems-sample:main
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [
          {buildx: linux/amd64, target_arch: amd64, os_version: debian},
          {buildx: linux/arm/v7, target_arch: armv7, os_version: debian},
          {buildx: linux/arm/v7, target_arch: armhf, os_version: raspbian},
          {buildx: linux/arm64,  target_arch: aarch64, os_version: debian}
        ]
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/openhems:latest
          platforms: ${{ matrix.platform.buildx }}
          build-args: |
            TARGETARCH=${{ matrix.platform.target_arch }}
            os_version=${{ matrix.platform.os_version }}
          tags: openhems
          load: true
      - name: Test # Run docker for 2min, if the output contains waitress   INFO  "Serving on" http://0.0.0.0:5000 assume it worked
        run: timeout 2 openhems run --rm -it openhems | grep -q "HTTP server is listening"  && echo 0 || echo 1
